# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/
# wallpaper {
#     monitor = eDP-1
#     path = /usr/share/hypr/wall2.png
#     fit_mode = cover
# }
preload = /usr/share/hypr/wall2.png
wallpaper = ,/usr/share/hypr/wall2.png
